### ISSUE TITLE
Reunião com GTCESP

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#19]
Origem da demanda: https://github.com/EscolaDeSaudePublica/Selecoes/issues/18

Marcar reunião sobre editais, em especial o Edital 04/2020 (https://github.com/EscolaDeSaudePublica/SACS/issues/93).

**Comment by helenhilario** [comment]
Agenda com o GTCESP, ficou marcada para quarta-feira (10/06/2020) de 9h às 10h.
Será adicionado na nossa Agenda compartilhada do Google.
