### ISSUE TITLE
1ª Edição: Testes de uso do Mapas

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#34]
Relatório de uso do Mapas no endereço: https://homolog.mapacultural.secult.ce.gov.br/

Aconteceu, no dia **01/09/2020**, a **1ª apresentação, focada para a área administrativa**: #41 .

**Comment by rafaelmassuncao** [comment]
**Rafael (@rmadev-master ):** (adicionar observações)
**Mayara (@MayaraMonte ):** (adicionar observações)
**Luciana Lopes:** (adicionar observações)
**Ricardo Silva:** (adicionar observações)

**Comment by Junior-Shyko** [comment]
Agendado com o @rodrigoplimafreire e mais algumas pessoas para sexta criar uma oportunidade com a visão administrativa.

**Comment by Junior-Shyko** [comment]
Teste com base no edital 07. [Edital](https://www.esp.ce.gov.br/2020/08/03/edital-07-2020/)
