### ISSUE TITLE
2ª Sessão do Workshop Inception com os envolvidos no projeto Seleções/Maps

### ISSUE THREAD

**Issue by rodrigoplimafreire** [FeliciLab/Selecoes#44]
**Data e Hora:** 28/08/2020, das 14h30 a 16h30

**Convidados Confirmados:**

- Caio Cavalcanti (Adins)
- Francisco Júnior (@Junior-Shyko )
- Luciana Magalhães (GT)
- Patrícia Azevedo (Asjur)
- Rafael Moreira (@rmadev-master )
- Rodrigo Freire (@rodrigoplimafreire )
- Uirá Maia (@uira )
- Victor Pacheco (@victorMagalhaesPacheco )
- Wilma Lins (Adins)

**Convidados Presentes:**

- Francisco Júnior (@Junior-Shyko )
- Luciana Magalhães (GT)
- Rafael Moreira (@rmadev-master )
- Rodrigo Freire (@rodrigoplimafreire )
- Matheus (@matheuscpl )
- Mayara Monte (@MayaraMonte )

**Metodologia:**

Lean Inception: é um workshop colaborativo para alinhar os envolvidos e definir um produto mínimo viável (MVP) a ser desenvolvido.

**Pauta:**

- Continuar e aprofundar no entendimento do projeto e na construção da 1ª MVP.

**Temas abordados:**

- Kick-off do Produto
- É/Não é - Faz/Não faz
- Visão do Produto
- Objetivos do Produto
- Personas e Jornadas
- Brainstorming de Funcionalidades (Features)﻿

**Link do Miro:** 

https://miro.com/welcomeonboard/amXc3ixGqzQPaPAnq4VMXGULe4hqJZDsSolEqLj8TZrQvQ7elyZSwEJXKu3YGP9x

**Comment by rafaelmassuncao** [comment]
Reunião encerrada, às 15h20, por de falta de quórum.
