### ISSUE TITLE
Integração com Keycloak

### ISSUE THREAD

**Issue by Junior-Shyko** [FeliciLab/Selecoes#46]
Criar a integração do ID saúde ([Relaciona com issue 20 do ID SAUDE](https://github.com/EscolaDeSaudePublica/IdentidadeUnicaDeSaude/issues/20) )

- [x] Subir branch para repositório [Escola de saúde](https://github.com/EscolaDeSaudePublica)

**Comment by Junior-Shyko** [comment]
Branch https://github.com/EscolaDeSaudePublica/MapaDaSaude/tree/feature/keycloak

**Comment by uira** [comment]
![image](https://user-images.githubusercontent.com/89998/92033518-2ace2980-ed42-11ea-9f45-8d8590e7f158.png)


@Junior-Shyko

**Comment by rafaelmassuncao** [comment]
Aguardando aprovação do Rafael (Hacklab) para o check 02.
