### ISSUE TITLE
Criar DER - Modelo Inicial

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#6]
Link: https://drive.google.com/file/d/1LCdCqeQ_Smttakl4QY8mKgBrNB9FbOXf/view?usp=sharing

**Comment by rmadev-master** [comment]
Link: https://drive.google.com/file/d/1swqZjNR7yaxfNo__J2pBXrYvugbwj06l/view?usp=sharing

**Comment by rafaelmassuncao** [comment]
Primeiro modelo finalizado
