### ISSUE TITLE
Edital 15/2020 - CEATS

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#62]
<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/23" target="_blank">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
    <td><a href="https://trello.com/c/bulUcmCt/19-edital-15-2020-ceats-projeto-de-ed-permanente-em-transplantes" target="_blank">clique aqui</a></td>
  </tr>
</body>
</table>

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Detalhamento das ações</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Quadro do projeto</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/23" target="_blank">clique aqui</a></td>
  </tr>
</body>
</table>

**Etapas:** 

- [x] Análise do edital (calendário, etapas, pontuação, etc)
- [x] Criar do edital do Sisweb/SIGRH
- [x] Criar a estrutura de banco
- [x] Implementar e testar
- [x] Publicar o edital

**Comment by Junior-Shyko** [comment]
Concluído e publicado.
