### ISSUE TITLE
Definir nome/sigla do projeto

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#7]
A equipe deve se posicionar em definitivo sobre esse assunto.

**Comment by rafaelmassuncao** [comment]
**Opções:**

**1. _Nome:_**

- Sistema de Gerenciamento Unificado de Seleções;
- Solução Única de Seleções;
- Outro...

**2. _Sigla:_**

- SUSE;
- SELECT;
- Outro...

**Comment by ClarisCaval** [comment]
Solução Única de Seleções (SUSE), é meu voto.

*Clarisse Castro Cavalcante*
Jornalista - Doutora
Skype: clarisse.castro3
32. 991586986

**Comment by Junior-Shyko** [comment]
Solução única de seleções.

**Comment by rafaelmassuncao** [comment]
Foi definido em reunião, no dia 20/05/2020, das 11h30 as 13h, com a presença do Superintendente da ESP/CE, que o sistema teria o nome "**Sistema Integrado de Seleções**".
