### ISSUE TITLE
Edital 03/2021 - Adins

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#70]
### Objetivo
**Como** candidato de processo seletivo
**Quando** acessar o endereço de inscrições do Edital nº 03/2021 - Adins
**Então** quero realizar minha inscrição e participar de todas as etapas das quais for classificado dentro do processo.

### Escopo
O edital precisa estar no ar no dia 19/04/2021 conforme especificado.

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Acompanhamento do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/31">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
    <td><a href="#">não informado</a></td>
  </tr>
  <tr>
    <td>Página da ESP-CE</td>
    <td><a href="#">não informado</a></td>
  </tr>
  <tr>
    <td>Endereço do Sistema</td>
    <td><a href="http://selecoes.esp.ce.gov.br/2021/edt032021adins/">clique aqui</a></td>
  </tr>
</body>
</table>

**Critérios de Aceitação:** 
- [x] Edital analisado (calendário, etapas, pontuação, etc)
- [x] Edital criado no Sisweb/SIGRH
- [x] Criada a estrutura de banco
- [x] Implementado e testado
- [x] Publicado

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links das Issues dos Critérios de Aceitação</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Análise do edital (calendário, etapas, pontuação, etc)</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/217">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar o edital do Sisweb/SIGRH</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/218">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar a estrutura de banco</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/219">clique aqui</a></td>
  </tr>
  <tr>
    <td>Implementar e testar</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/220">clique aqui</a></td>
  </tr>
  <tr>
    <td>Publicar o edital</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/221">clique aqui</a></td>
  </tr>
</body>
</table>

**Comment by rafaelmassuncao** [comment]
**Edital:** 
[clique aqui](https://github.com/EscolaDeSaudePublica/Selecoes/files/6189213/EDITAL.03.2021.-.ADINS.pdf)

**Comment by rafaelmassuncao** [comment]
### Observações
Alterações foram feitas no Edital e não foi comunicado à equipe com antecedência. Essas alterações demandam mais tempo de produção e obviamente, maior prazo na entrega.

1. Dois setores como demandantes da seleção ao invés de um: a homologação "sofrerá" com a mudança e somente será possível alterar o setor primário, até depois da homologação, via solicitação por escrito.
2. Foi adicionado um critério de nota mínima sobre a nota final. Essa alteração afetará o cálculo dos resultados que precisam ser rastreados e atualizados em todo o sistema.

**Comment by rafaelmassuncao** [comment]
**Uma nova versão do Edital foi disponibilizada:** [2021-04-09](https://github.com/EscolaDeSaudePublica/Selecoes/files/6286381/edital.pdf)

**Comment by glaucia-posso** [comment]
rever edital

**Comment by rmadev-master** [comment]
Em andamento.

**Comment by glaucia-posso** [comment]
> **Uma nova versão do Edital foi disponibilizada:** [2021-04-09](https://github.com/EscolaDeSaudePublica/Selecoes/files/6286381/edital.pdf)

visualizado

**Comment by uira** [comment]
@glaucia-posso 🌈🌈🌈

**Comment by rafaelmassuncao** [comment]
Link: http://selecoes.esp.ce.gov.br/2021/edt032021adins/
