### ISSUE TITLE
Edital 09/2021 - CENIC

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/Selecoes#75]
### Objetivo
**Como** candidato de processo seletivo
**Quando** acessar o endereço de inscrições do Edital nº 09/2021 - CENIC
**Então** quero realizar minha inscrição e participar de todas as etapas das quais for classificado dentro do processo.

### Escopo
O edital precisa estar no ar no dia 28/05/2021 conforme especificado.

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Acompanhamento do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/37">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
    <td><a href="#">não informado</a></td>
  </tr>
  <tr>
    <td>Página da ESP-CE</td>
    <td><a href="https://www.esp.ce.gov.br/2021/05/24/edital-09-2021-bolsista-para-programa-de-gerenciamento-da-terapia-antimicrobiana-por-meio-da-reducao-de-desperdicio-e-aumento-da-eficiencia-em-unidades-hospitalares-de-referencia-da-secretaria-da-sau/">clique aqui</a></td>
  </tr>
  <tr>
    <td>Endereço do Sistema</td>
    <td><a href="http://selecoes.esp.ce.gov.br/2021/edt092021cenic/">clique aqui</a></td>
  </tr>
</body>
</table>

**Critérios de Aceitação:** 
- [x] Edital analisado (calendário, etapas, pontuação, etc) 
- [x] Edital criado no Sisweb/SIGRH
- [x] Criada a estrutura de banco
- [x] Implementado e testado 
- [x] Publicado

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links das Issues dos Critérios de Aceitação</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Análise do edital (calendário, etapas, pontuação, etc)</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/247">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar o edital do Sisweb/SIGRH</td>
     <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/248">clique aqui</a></td>

  </tr>
  <tr>
    <td>Criar a estrutura de banco</td>
        <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/249">clique aqui</a></td>

  </tr>
  <tr>
    <td>Implementar e testar</td>
      <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/250">clique aqui</a></td>

  </tr>
  <tr>
    <td>Publicar o edital</td>
      <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/251">clique aqui</a></td>

  </tr>
</body>
</table>

**Comment by luannaalves** [comment]
Edital 09/2021 - CENIC está em análise.

**Comment by luannaalves** [comment]
Edital analisado, apto a ser criado no Sisweb/SIGRH.

**Comment by rafaelmassuncao** [comment]
Concluído
