### ISSUE TITLE
Edital 10/2021 -  DIPSA/CEVIG 

### ISSUE THREAD

**Issue by luannaalves** [FeliciLab/Selecoes#76]
### Objetivo
**Como** candidato de processo seletivo
**Quando** acessar o endereço de inscrições do Edital nº 10/2021 - DIPSA/CEVIG
**Então** quero realizar minha inscrição e participar de todas as etapas das quais for classificado dentro do processo.

### Escopo
O edital precisa estar no ar no dia 04/06/2021 conforme especificado.

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Acompanhamento do Edital</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>GitHub</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/projects/38">clique aqui</a></td>
  </tr>
  <tr>
    <td>Trello</td>
    <td><a href="#">não informado</a></td>
  </tr>
  <tr>
    <td>Página da ESP-CE</td>
    <td><a href="https://www.esp.ce.gov.br/2021/05/26/edital-10-2021-curso-de-especializacao-em-vigilancia-sanitaria/">clique aqui</a></td>
  </tr>
  <tr>
    <td>Endereço do Sistema</td>
    <td><a href="http://selecoes.esp.ce.gov.br/2021/edt102021cevig/">clique aqui</a></td>
  </tr>
</body>
</table>

**Critérios de Aceitação:** 
- [x] Edital analisado (calendário, etapas, pontuação, etc)  
- [x] Edital criado no Sisweb/SIGRH 
- [x] Criada a estrutura de banco
- [x] Implementado e testado
- [x] Publicado :point_left:

<table border="1" align="center">
<thead>
  <tr>
    <td colspan="2"><strong>Links das Issues dos Critérios de Aceitação</strong></td>
  </tr>
</thead>
<body>
  <tr>
    <td>Análise do edital (calendário, etapas, pontuação, etc)</td>
    <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/252">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar o edital do Sisweb/SIGRH</td>
       <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/253">clique aqui</a></td>
  </tr>
  <tr>
    <td>Criar a estrutura de banco</td>
        <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/254">clique aqui</a></td>

  </tr>
  <tr>
    <td>Implementar e testar</td>
      <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/255">clique aqui</a></td>

  </tr>
  <tr>
    <td>Publicar o edital</td>
       <td><a href="https://github.com/EscolaDeSaudePublica/SACS/issues/256">clique aqui</a></td>

  </tr>
</body>
</table>

**Comment by luannaalves** [comment]
Edital analisado, apto a ser criado no Sisweb.

**Comment by rafaelmassuncao** [comment]
Upload do sistema realizado.
