### ISSUE TITLE
Registro de Reunião - 19/05/2020 - 09h10 - 09h40

### ISSUE THREAD

**Issue by rafaelmassuncao** [FeliciLab/Selecoes#8]
Pauta

1. Explicação sobre como será alimentado o GIT (backlogs e sprints);
2. Definir semanal (dia/hora);
3. Estrutura de banco/aplicação.

**Comment by rmadev-master** [comment]
https://app.diagrams.net/#G1swqZjNR7yaxfNo__J2pBXrYvugbwj06l

**Comment by rafaelmassuncao** [comment]
Resultados da Reunião:
[download](https://docs.google.com/document/d/198nsIKofrEHpE1nAUA_RbRG7RayZE7yKDjIY0BZmPcg/edit?usp=sharing)
